// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Structs
struct Triangle {
    // Byte size = 4 * 4 bytes = 16 total bytes
    int index;
    float3 vertA;
    float3 vertB;
    float3 vertC;
}

AppendStructuredBuffer<Triangle> triangles;

[numthreads(16,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!
    Result[id.xy] = float4(id.x & id.y, (id.x & 15)/15.0, (id.y & 15)/15.0, 0.0);
}
